# infrastructure/ansible/inventory.ini
[webservers]
# Add target server IPs or DNS names here later, e.g.:
# 1.2.3.4 ansible_user=ubuntu

[all:vars]
# Define global variables if needed, e.g.
# app_version=latest